# fly.toml app configuration file generated for indiejoa-api on 2024-05-29T11:58:21+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'indiejoa-api'
primary_region = 'nrt'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
