spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common

---
spring:
  config:
    activate:
      on-profile: common
  application:
    name: IndieJoa-API

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5678/indie-joa-database
    username: myuser
    password: mypassword